### ISSUE TITLE
README.md: broken link

### ISSUE THREAD

**Issue by cznic** [rsc/getopt#1]
> [For full package documentation, see https://godoc.org/rsc.io/getopt.]

At 10:51, Friday, 11 August 2017 (CEST) the site response after about a minute is

```
Internal server error.
```

**Comment by dmitshur** [comment]
Duplicate of https://github.com/golang/gddo/issues/502.

**Comment by rsc** [comment]
Closed as duplicate. Thanks @shurcooL.
